language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
   - SYMFONY_VERSION="~2.3,<2.4.0" DOCTRINE_VERSION="~2.3,<2.4.0"
   - SYMFONY_VERSION="~2.3,<2.4.0" DOCTRINE_VERSION="~2.4,<2.5.0"
   - SYMFONY_VERSION="~2.3,<2.4.0" DOCTRINE_VERSION="~2.5,<2.6.0"
   - SYMFONY_VERSION="~2.4,<2.5.0" DOCTRINE_VERSION="~2.3,<2.4.0"
   - SYMFONY_VERSION="~2.4,<2.5.0" DOCTRINE_VERSION="~2.4,<2.5.0"
   - SYMFONY_VERSION="~2.4,<2.5.0" DOCTRINE_VERSION="~2.5,<2.6.0"
   - SYMFONY_VERSION="~2.5,<2.6.0" DOCTRINE_VERSION="~2.3,<2.4.0"
   - SYMFONY_VERSION="~2.5,<2.6.0" DOCTRINE_VERSION="~2.4,<2.5.0"
   - SYMFONY_VERSION="~2.5,<2.6.0" DOCTRINE_VERSION="~2.5,<2.6.0"
   - SYMFONY_VERSION="~2.6,<2.7.0" DOCTRINE_VERSION="~2.3,<2.4.0"
   - SYMFONY_VERSION="~2.6,<2.7.0" DOCTRINE_VERSION="~2.4,<2.5.0"
   - SYMFONY_VERSION="~2.6,<2.7.0" DOCTRINE_VERSION="~2.5,<2.6.0"

services:
  - mongodb

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly

  include:
    - php: 7.0
      env: SYMFONY_VERSION="~2.6" DOCTRINE_VERSION="~2.5"
    - php: hhvm
      env: SYMFONY_VERSION="~2.6" DOCTRINE_VERSION="~2.5"
    - php: hhvm-nightly
      env: SYMFONY_VERSION="~2.6" DOCTRINE_VERSION="~2.5"

  exclude:
    - php: 5.3
      env: SYMFONY_VERSION="~2.3,<2.4.0" DOCTRINE_VERSION="~2.5,<2.6.0"
    - php: 5.3
      env: SYMFONY_VERSION="~2.4,<2.5.0" DOCTRINE_VERSION="~2.5,<2.6.0"
    - php: 5.3
      env: SYMFONY_VERSION="~2.5,<2.6.0" DOCTRINE_VERSION="~2.5,<2.6.0"
    - php: 5.3
      env: SYMFONY_VERSION="~2.6,<2.7.0" DOCTRINE_VERSION="~2.5,<2.6.0"

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != 'hhvm-nightly' && $TRAVIS_PHP_VERSION != '7.0' ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer self-update
  - composer require --ignore-platform-reqs doctrine/common:~2.4 doctrine/dbal:${DOCTRINE_VERSION} doctrine/orm:${DOCTRINE_VERSION} symfony/framework-bundle:${SYMFONY_VERSION} symfony/symfony:${SYMFONY_VERSION} symfony/framework-bundle:${SYMFONY_VERSION}
  - if [[ $TRAVIS_PHP_VERSION == 'hhvm' || $TRAVIS_PHP_VERSION == 'hhvm-nightly' || $TRAVIS_PHP_VERSION == '7.0' ]]; then composer require --dev mongofill/mongofill=dev-master --no-update; fi
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != 'hhvm-nightly' && $TRAVIS_PHP_VERSION != '7.0' ]]; then composer install; fi
  - if [[ $TRAVIS_PHP_VERSION == 'hhvm' || $TRAVIS_PHP_VERSION == 'hhvm-nightly' || $TRAVIS_PHP_VERSION == '7.0' ]]; then composer install --ignore-platform-reqs; fi

script: ./vendor/bin/phpunit  --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $COMPOSER_CACHE_DIR

notifications:
  email:
    - stosh1985@gmail.com
